# Usage: conda env create -f condaQGIS_env.yaml

name: condaQGIS
channels:
  - conda-forge
  - anaconda
  - menpo
  - defaults
dependencies:
  - python==3.12.3  # QGIS currently using 3.12.3 (The system default for my version of Ubuntu)
  - gdal==3.8.4     # Deliberately using the same version as QGIS
  - libtiff==4.6.1  # This is shared between conda and QGIS dependencies
  - rasterio        # Requires libtiff version 4.6.1 to match qgis
  - rasterstats     # Requires libtiff version 4.6.1 to match qgis
  - contextily      # Requires libtiff version 4.6.1 to match qgis
  - matplotlib      # QGIS uses 3.6.3, which conflicts with Python 3.12.3
  - numpy==1.26.4
  - pyproj==3.6.1
  - qgis  
  - scipy
  - ipython
  - jupyter
  - joblib
  - scikit-learn
  - seaborn
  - plotly
  - plotly_express
  - python-dotenv
  #- polars #conflicts with Python 3.12.3
  - pandas
  - geopandas
  - shapely
  - cartopy
  - geoplot
  - ipyleaflet
  - folium
  - pillow
  - geoviews
  - opencv
  - fastparquet
  - pyarrow
  - pyyaml
  - piexif
  - xmltodict
  - pip
  - pip:
    #- some crazy package only availabl on pip
      
# TorchGeo extra packages
#  - pytorch-lightning=2.0.6
#  - torchvision=0.16
#  - timm=0.9.7 
#  - scikit-image=0.21.0
#  - seaborn=0.12.2
#  - albumentations=1.3.1
#  - python-kaleido=0.2.1